export const SubjectDatabase = {
  "food": [
    { "emoji": "🍕", "names": { "en": "Pizza", "ar": "بيتزا", "ja": "ピザ", "zh": "披萨", "ko": "피자", "de": "Pizza", "fr": "Pizza", "pt": "Pizza", "es": "Pizza" } },
    { "emoji": "🍣", "names": { "en": "Sushi", "ar": "سوشي", "ja": "寿司", "zh": "寿司", "ko": "스시", "de": "Sushi", "fr": "Sushi", "pt": "Sushi", "es": "Sushi" } },
    { "emoji": "🍔", "names": { "en": "Hamburger", "ar": "برجر", "ja": "ハンバーガー", "zh": "汉堡", "ko": "햄버거", "de": "Hamburger", "fr": "Hamburger", "pt": "Hambúrguer", "es": "Hamburguesa" } },
    { "emoji": "🍦", "names": { "en": "Ice Cream", "ar": "آيس كريم", "ja": "アイスクリーム", "zh": "冰淇淋", "ko": "아이스크림", "de": "Eis", "fr": "Glace", "pt": "Sorvete", "es": "Helado" } },
    { "emoji": "🍫", "names": { "en": "Chocolate", "ar": "شوكولاتة", "ja": "チョコレート", "zh": "巧克力", "ko": "초콜릿", "de": "Schokolade", "fr": "Chocolat", "pt": "Chocolate", "es": "Chocolate" } },
    { "emoji": "🍜", "names": { "en": "Ramen", "ar": "رامن", "ja": "ラーメン", "zh": "拉面", "ko": "라면", "de": "Ramen", "fr": "Ramen", "pt": "Ramen", "es": "Ramen" } },
    { "emoji": "🌮", "names": { "en": "Tacos", "ar": "تاكو", "ja": "タコス", "zh": "墨西哥卷", "ko": "타코", "de": "Tacos", "fr": "Tacos", "pt": "Tacos", "es": "Tacos" } },
    { "emoji": "☕", "names": { "en": "Coffee", "ar": "قهوة", "ja": "コーヒー", "zh": "咖啡", "ko": "커피", "de": "Kaffee", "fr": "Café", "pt": "Café", "es": "Café" } },
    { "emoji": "🍌", "names": { "en": "Banana", "ar": "موز", "ja": "バナナ", "zh": "香蕉", "ko": "바나나", "de": "Banane", "fr": "Banane", "pt": "Banana", "es": "Plátano" } },
    { "emoji": "🎂", "names": { "en": "Cake", "ar": "كعكة", "ja": "ケーキ", "zh": "蛋糕", "ko": "케이크", "de": "Kuchen", "fr": "Gâteau", "pt": "Bolo", "es": "Pastel" } },
    { "emoji": "🍩", "names": { "en": "Donut", "ar": "دونات", "ja": "ドーナツ", "zh": "甜甜圈", "ko": "도넛", "de": "Donut", "fr": "Beignet", "pt": "Rosquinha", "es": "Dona" } },
    { "emoji": "🍟", "names": { "en": "French Fries", "ar": "بطاطا مقلية", "ja": "フライドポテト", "zh": "薯条", "ko": "감자튀김", "de": "Pommes", "fr": "Frites", "pt": "Batata Frita", "es": "Papas Fritas" } },
    { "emoji": "🍝", "names": { "en": "Pasta", "ar": "باستا", "ja": "パスタ", "zh": "意大利面", "ko": "파스타", "de": "Pasta", "fr": "Pâtes", "pt": "Macarrão", "es": "Pasta" } },
    { "emoji": "🥟", "names": { "en": "Dumplings", "ar": "دمبلينغ", "ja": "餃子", "zh": "饺子", "ko": "만두", "de": "Teigtaschen", "fr": "Raviolis", "pt": "Guioza", "es": "Dumplings" } },
    { "emoji": "🥐", "names": { "en": "Croissant", "ar": "كرواسون", "ja": "クロワッサン", "zh": "牛角包", "ko": "크루아상", "de": "Croissant", "fr": "Croissant", "pt": "Croissant", "es": "Croissant" } },
    { "emoji": "🍛", "names": { "en": "Curry", "ar": "كاري", "ja": "カレー", "zh": "咖喱", "ko": "카레", "de": "Curry", "fr": "Curry", "pt": "Curry", "es": "Curry" } },
    { "emoji": "🧇", "names": { "en": "Waffles", "ar": "وافل", "ja": "ワッフル", "zh": "华夫饼", "ko": "와플", "de": "Waffeln", "fr": "Gaufres", "pt": "Waffles", "es": "Gofres" } },
    { "emoji": "🍿", "names": { "en": "Popcorn", "ar": "فشار", "ja": "ポップコーン", "zh": "爆米花", "ko": "팝콘", "de": "Popcorn", "fr": "Pop-corn", "pt": "Pipoca", "es": "Palomitas" } },
    { "emoji": "🥩", "names": { "en": "Steak", "ar": "ستيك", "ja": "ステーキ", "zh": "牛排", "ko": "스테이크", "de": "Steak", "fr": "Steak", "pt": "Bife", "es": "Filete" } },
    { "emoji": "🍗", "names": { "en": "Fried Chicken", "ar": "دجاج مقلي", "ja": "フライドチキン", "zh": "炸鸡", "ko": "프라이드치킨", "de": "Brathähnchen", "fr": "Poulet frit", "pt": "Frango Frito", "es": "Pollo Frito" } },
    { "emoji": "🥗", "names": { "en": "Salad", "ar": "سلطة", "ja": "サラダ", "zh": "沙拉", "ko": "샐러드", "de": "Salat", "fr": "Salade", "pt": "Salada", "es": "Ensalada" } },
    { "emoji": "🌭", "names": { "en": "Hot Dog", "ar": "هوت دوغ", "ja": "ホットドッグ", "zh": "热狗", "ko": "핫도그", "de": "Hotdog", "fr": "Hot-dog", "pt": "Cachorro-quente", "es": "Perrito caliente" } },
    { "emoji": "🥪", "names": { "en": "Sandwich", "ar": "ساندويش", "ja": "サンドイッチ", "zh": "三明治", "ko": "샌드위치", "de": "Sandwich", "fr": "Sandwich", "pt": "Sanduíche", "es": "Sándwich" } },
    { "emoji": "🍜", "names": { "en": "Pho", "ar": "فو", "ja": "フォー", "zh": "河粉", "ko": "쌀국수", "de": "Pho", "fr": "Pho", "pt": "Pho", "es": "Pho" } },
    { "emoji": "🥞", "names": { "en": "Pancakes", "ar": "بانكيك", "ja": "パンケーキ", "zh": "煎饼", "ko": "팬케이크", "de": "Pfannkuchen", "fr": "Crêpes", "pt": "Panquecas", "es": "Panqueques" } },
    { "emoji": "🫕", "names": { "en": "Kebab", "ar": "كباب", "ja": "ケバブ", "zh": "烤肉串", "ko": "케밥", "de": "Kebab", "fr": "Kebab", "pt": "Kebab", "es": "Kebab" } },
    { "emoji": "🥘", "names": { "en": "Paella", "ar": "باييلا", "ja": "パエリア", "zh": "西班牙海鲜饭", "ko": "파에야", "de": "Paella", "fr": "Paella", "pt": "Paella", "es": "Paella" } },
    { "emoji": "🍰", "names": { "en": "Cheesecake", "ar": "كيك الجبن", "ja": "チーズケーキ", "zh": "芝士蛋糕", "ko": "치즈케이크", "de": "Käsekuchen", "fr": "Cheesecake", "pt": "Cheesecake", "es": "Tarta de queso" } },
    { "emoji": "🍲", "names": { "en": "Spring Rolls", "ar": "لفائف الربيع", "ja": "春巻き", "zh": "春卷", "ko": "춘권", "de": "Frühlingsrollen", "fr": "Rouleaux de printemps", "pt": "Rolinho primavera", "es": "Rollitos de primavera" } }
  ],
  "animals": [
    { "emoji": "🦁", "names": { "en": "Lion", "ar": "أسد", "ja": "ライオン", "zh": "狮子", "ko": "사자", "de": "Löwe", "fr": "Lion", "pt": "Leão", "es": "León" } },
    { "emoji": "🐘", "names": { "en": "Elephant", "ar": "فيل", "ja": "ゾウ", "zh": "大象", "ko": "코끼리", "de": "Elefant", "fr": "Éléphant", "pt": "Elefante", "es": "Elefante" } },
    { "emoji": "🐧", "names": { "en": "Penguin", "ar": "بطريق", "ja": "ペンギン", "zh": "企鹅", "ko": "펭귄", "de": "Pinguin", "fr": "Pingouin", "pt": "Pinguim", "es": "Pingüino" } },
    { "emoji": "🦒", "names": { "en": "Giraffe", "ar": "زرافة", "ja": "キリン", "zh": "长颈鹿", "ko": "기린", "de": "Giraffe", "fr": "Girafe", "pt": "Girafa", "es": "Jirafa" } },
    { "emoji": "🐬", "names": { "en": "Dolphin", "ar": "دلفين", "ja": "イルカ", "zh": "海豚", "ko": "돌고래", "de": "Delphin", "fr": "Dauphin", "pt": "Golfinho", "es": "Delfín" } },
    { "emoji": "🐼", "names": { "en": "Panda", "ar": "باندا", "ja": "パンダ", "zh": "熊猫", "ko": "판다", "de": "Panda", "fr": "Panda", "pt": "Panda", "es": "Panda" } },
    { "emoji": "🦜", "names": { "en": "Parrot", "ar": "ببغاء", "ja": "オウム", "zh": "鹦鹉", "ko": "앵무새", "de": "Papagei", "fr": "Perroquet", "pt": "Papagaio", "es": "Loro" } },
    { "emoji": "🐯", "names": { "en": "Tiger", "ar": "نمر", "ja": "トラ", "zh": "老虎", "ko": "호랑이", "de": "Tiger", "fr": "Tigre", "pt": "Tigre", "es": "Tigre" } },
    { "emoji": "🦘", "names": { "en": "Kangaroo", "ar": "كنغر", "ja": "カンガルー", "zh": "袋鼠", "ko": "캥거루", "de": "Känguru", "fr": "Kangourou", "pt": "Canguru", "es": "Canguro" } },
    { "emoji": "🐙", "names": { "en": "Octopus", "ar": "أخطبوط", "ja": "タコ", "zh": "章鱼", "ko": "문어", "de": "Tintenfisch", "fr": "Pieuvre", "pt": "Polvo", "es": "Pulpo" } },
    { "emoji": "🦊", "names": { "en": "Fox", "ar": "ثعلب", "ja": "キツネ", "zh": "狐狸", "ko": "여우", "de": "Fuchs", "fr": "Renard", "pt": "Raposa", "es": "Zorro" } },
    { "emoji": "🦋", "names": { "en": "Butterfly", "ar": "فراشة", "ja": "チョウ", "zh": "蝴蝶", "ko": "나비", "de": "Schmetterling", "fr": "Papillon", "pt": "Borboleta", "es": "Mariposa" } },
    { "emoji": "🐻", "names": { "en": "Bear", "ar": "دب", "ja": "クマ", "zh": "熊", "ko": "곰", "de": "Bär", "fr": "Ours", "pt": "Urso", "es": "Oso" } },
    { "emoji": "🦈", "names": { "en": "Shark", "ar": "قرش", "ja": "サメ", "zh": "鲨鱼", "ko": "상어", "de": "Hai", "fr": "Requin", "pt": "Tubarão", "es": "Tiburón" } },
    { "emoji": "🦅", "names": { "en": "Eagle", "ar": "نسر", "ja": "ワシ", "zh": "鹰", "ko": "독수리", "de": "Adler", "fr": "Aigle", "pt": "Águia", "es": "Águila" } },
    { "emoji": "🐎", "names": { "en": "Horse", "ar": "حصان", "ja": "馬", "zh": "马", "ko": "말", "de": "Pferd", "fr": "Cheval", "pt": "Cavalo", "es": "Caballo" } },
    { "emoji": "🐢", "names": { "en": "Turtle", "ar": "سلحفاة", "ja": "カメ", "zh": "海龟", "ko": "거북이", "de": "Schildkröte", "fr": "Tortue", "pt": "Tartaruga", "es": "Tortuga" } },
    { "emoji": "🐪", "names": { "en": "Camel", "ar": "جمل", "ja": "ラクダ", "zh": "骆驼", "ko": "낙타", "de": "Kamel", "fr": "Chameau", "pt": "Camelo", "es": "Camello" } },
    { "emoji": "🦩", "names": { "en": "Flamingo", "ar": "فلامنغو", "ja": "フラミンゴ", "zh": "火烈鸟", "ko": "플라밍고", "de": "Flamingo", "fr": "Flamant rose", "pt": "Flamingo", "es": "Flamenco" } },
    { "emoji": "🐊", "names": { "en": "Crocodile", "ar": "تمساح", "ja": "ワニ", "zh": "鳄鱼", "ko": "악어", "de": "Krokodil", "fr": "Crocodile", "pt": "Crocodilo", "es": "Cocodrilo" } },
    { "emoji": "🐨", "names": { "en": "Koala", "ar": "كوالا", "ja": "コアラ", "zh": "考拉", "ko": "코알라", "de": "Koala", "fr": "Koala", "pt": "Coala", "es": "Koala" } },
    { "emoji": "🐺", "names": { "en": "Wolf", "ar": "ذئب", "ja": "オオカミ", "zh": "狼", "ko": "늑대", "de": "Wolf", "fr": "Loup", "pt": "Lobo", "es": "Lobo" } },
    { "emoji": "🦚", "names": { "en": "Peacock", "ar": "طاووس", "ja": "クジャク", "zh": "孔雀", "ko": "공작", "de": "Pfau", "fr": "Paon", "pt": "Pavão", "es": "Pavo real" } },
    { "emoji": "🦀", "names": { "en": "Crab", "ar": "سرطان البحر", "ja": "カニ", "zh": "螃蟹", "ko": "게", "de": "Krabbe", "fr": "Crabe", "pt": "Caranguejo", "es": "Cangrejo" } },
    { "emoji": "🦉", "names": { "en": "Owl", "ar": "بومة", "ja": "フクロウ", "zh": "猫头鹰", "ko": "올빼미", "de": "Eule", "fr": "Hibou", "pt": "Coruja", "es": "Búho" } },
    { "emoji": "🐆", "names": { "en": "Cheetah", "ar": "فهد", "ja": "チーター", "zh": "猎豹", "ko": "치타", "de": "Gepard", "fr": "Guépard", "pt": "Guepardo", "es": "Guepardo" } },
    { "emoji": "🦍", "names": { "en": "Gorilla", "ar": "غوريلا", "ja": "ゴリラ", "zh": "大猩猩", "ko": "고릴라", "de": "Gorilla", "fr": "Gorille", "pt": "Gorila", "es": "Gorila" } },
    { "emoji": "🐸", "names": { "en": "Frog", "ar": "ضفدع", "ja": "カエル", "zh": "青蛙", "ko": "개구리", "de": "Frosch", "fr": "Grenouille", "pt": "Sapo", "es": "Rana" } },
    { "emoji": "🦓", "names": { "en": "Zebra", "ar": "حمار وحشي", "ja": "シマウマ", "zh": "斑马", "ko": "얼룩말", "de": "Zebra", "fr": "Zèbre", "pt": "Zebra", "es": "Cebra" } }
  ],
  "countries": [
    { "emoji": "🇯🇵", "names": { "en": "Japan", "ar": "اليابان", "ja": "日本", "zh": "日本", "ko": "일본", "de": "Japan", "fr": "Japon", "pt": "Japão", "es": "Japón" } },
    { "emoji": "🇧🇷", "names": { "en": "Brazil", "ar": "البرازيل", "ja": "ブラジル", "zh": "巴西", "ko": "브라질", "de": "Brasilien", "fr": "Brésil", "pt": "Brasil", "es": "Brasil" } },
    { "emoji": "🇪🇬", "names": { "en": "Egypt", "ar": "مصر", "ja": "エジプト", "zh": "埃及", "ko": "이집트", "de": "Ägypten", "fr": "Égypte", "pt": "Egito", "es": "Egipto" } },
    { "emoji": "🇨🇦", "names": { "en": "Canada", "ar": "كندا", "ja": "カナダ", "zh": "加拿大", "ko": "캐나다", "de": "Kanada", "fr": "Canada", "pt": "Canadá", "es": "Canadá" } },
    { "emoji": "🇫🇷", "names": { "en": "France", "ar": "فرنسا", "ja": "フランス", "zh": "法国", "ko": "프랑스", "de": "Frankreich", "fr": "France", "pt": "França", "es": "Francia" } },
    { "emoji": "🇦🇺", "names": { "en": "Australia", "ar": "أستراليا", "ja": "オーストラリア", "zh": "澳大利亚", "ko": "호주", "de": "Australien", "fr": "Australie", "pt": "Austrália", "es": "Australia" } },
    { "emoji": "🇲🇽", "names": { "en": "Mexico", "ar": "المكسيك", "ja": "メキシコ", "zh": "墨西哥", "ko": "멕시코", "de": "Mexiko", "fr": "Mexique", "pt": "México", "es": "México" } },
    { "emoji": "🇮🇳", "names": { "en": "India", "ar": "الهند", "ja": "インド", "zh": "印度", "ko": "인도", "de": "Indien", "fr": "Inde", "pt": "Índia", "es": "India" } },
    { "emoji": "🇮🇹", "names": { "en": "Italy", "ar": "إيطاليا", "ja": "イタリア", "zh": "意大利", "ko": "이탈리아", "de": "Italien", "fr": "Italie", "pt": "Itália", "es": "Italia" } },
    { "emoji": "🇰🇷", "names": { "en": "South Korea", "ar": "كوريا الجنوبية", "ja": "韓国", "zh": "韩国", "ko": "대한민국", "de": "Südkorea", "fr": "Corée du Sud", "pt": "Coreia do Sul", "es": "Corea del Sur" } },
    { "emoji": "🇸🇦", "names": { "en": "Saudi Arabia", "ar": "المملكة العربية السعودية", "ja": "サウジアラビア", "zh": "沙特阿拉伯", "ko": "사우디아라비아", "de": "Saudi-Arabien", "fr": "Arabie Saoudite", "pt": "Arábia Saudita", "es": "Arabia Saudita" } },
    { "emoji": "🇩🇪", "names": { "en": "Germany", "ar": "ألمانيا", "ja": "ドイツ", "zh": "德国", "ko": "독일", "de": "Deutschland", "fr": "Allemagne", "pt": "Alemanha", "es": "Alemania" } },
    { "emoji": "🇺🇸", "names": { "en": "USA", "ar": "الولايات المتحدة", "ja": "アメリカ", "zh": "美国", "ko": "미국", "de": "USA", "fr": "États-Unis", "pt": "EUA", "es": "Estados Unidos" } },
    { "emoji": "🇨🇳", "names": { "en": "China", "ar": "الصين", "ja": "中国", "zh": "中国", "ko": "중국", "de": "China", "fr": "Chine", "pt": "China", "es": "China" } },
    { "emoji": "🇬🇧", "names": { "en": "UK", "ar": "المملكة المتحدة", "ja": "イギリス", "zh": "英国", "ko": "영국", "de": "Großbritannien", "fr": "Royaume-Uni", "pt": "Reino Unido", "es": "Reino Unido" } },
    { "emoji": "🇪🇸", "names": { "en": "Spain", "ar": "إسبانيا", "ja": "スペイン", "zh": "西班牙", "ko": "스페인", "de": "Spanien", "fr": "Espagne", "pt": "Espanha", "es": "España" } },
    { "emoji": "🇹🇷", "names": { "en": "Turkey", "ar": "تركيا", "ja": "トルコ", "zh": "土耳其", "ko": "터키", "de": "Türkei", "fr": "Turquie", "pt": "Turquia", "es": "Turquía" } },
    { "emoji": "🇳🇬", "names": { "en": "Nigeria", "ar": "نيجيريا", "ja": "ナイジェリア", "zh": "尼日利亚", "ko": "나이지리아", "de": "Nigeria", "fr": "Nigéria", "pt": "Nigéria", "es": "Nigeria" } },
    { "emoji": "🇦🇷", "names": { "en": "Argentina", "ar": "الأرجنتين", "ja": "アルゼンチン", "zh": "阿根廷", "ko": "아르헨티나", "de": "Argentinien", "fr": "Argentine", "pt": "Argentina", "es": "Argentina" } },
    { "emoji": "🇹🇭", "names": { "en": "Thailand", "ar": "تايلاند", "ja": "タイ", "zh": "泰国", "ko": "태국", "de": "Thailand", "fr": "Thaïlande", "pt": "Tailândia", "es": "Tailandia" } },
    { "emoji": "🇳🇴", "names": { "en": "Norway", "ar": "النرويج", "ja": "ノルウェー", "zh": "挪威", "ko": "노르웨이", "de": "Norwegen", "fr": "Norvège", "pt": "Noruega", "es": "Noruega" } },
    { "emoji": "🇬🇷", "names": { "en": "Greece", "ar": "اليونان", "ja": "ギリシャ", "zh": "希腊", "ko": "그리스", "de": "Griechenland", "fr": "Grèce", "pt": "Grécia", "es": "Grecia" } },
    { "emoji": "🇰🇪", "names": { "en": "Kenya", "ar": "كينيا", "ja": "ケニア", "zh": "肯尼亚", "ko": "케냐", "de": "Kenia", "fr": "Kenya", "pt": "Quênia", "es": "Kenia" } },
    { "emoji": "🇲🇦", "names": { "en": "Morocco", "ar": "المغرب", "ja": "モロッコ", "zh": "摩洛哥", "ko": "모로코", "de": "Marokko", "fr": "Maroc", "pt": "Marrocos", "es": "Marruecos" } },
    { "emoji": "🇿🇦", "names": { "en": "South Africa", "ar": "جنوب أفريقيا", "ja": "南アフリカ", "zh": "南非", "ko": "남아프리카", "de": "Südafrika", "fr": "Afrique du Sud", "pt": "África do Sul", "es": "Sudáfrica" } },
    { "emoji": "🇮🇩", "names": { "en": "Indonesia", "ar": "إندونيسيا", "ja": "インドネシア", "zh": "印度尼西亚", "ko": "인도네시아", "de": "Indonesien", "fr": "Indonésie", "pt": "Indonésia", "es": "Indonesia" } },
    { "emoji": "🇸🇪", "names": { "en": "Sweden", "ar": "السويد", "ja": "スウェーデン", "zh": "瑞典", "ko": "스웨덴", "de": "Schweden", "fr": "Suède", "pt": "Suécia", "es": "Suecia" } },
    { "emoji": "🇦🇪", "names": { "en": "UAE", "ar": "الإمارات", "ja": "アラブ首長国連邦", "zh": "阿联酋", "ko": "아랍에미리트", "de": "VAE", "fr": "Émirats arabes", "pt": "Emirados", "es": "Emiratos" } },
    { "emoji": "🇵🇰", "names": { "en": "Pakistan", "ar": "باكستان", "ja": "パキスタン", "zh": "巴基斯坦", "ko": "파키스탄", "de": "Pakistan", "fr": "Pakistan", "pt": "Paquistão", "es": "Pakistán" } }
  ],
  "sports": [
    { "emoji": "⚽", "names": { "en": "Soccer", "ar": "كرة القدم", "ja": "サッカー", "zh": "足球", "ko": "축구", "de": "Fußball", "fr": "Football", "pt": "Futebol", "es": "Fútbol" } },
    { "emoji": "🏀", "names": { "en": "Basketball", "ar": "كرة السلة", "ja": "バスケットボール", "zh": "篮球", "ko": "농구", "de": "Basketball", "fr": "Basketball", "pt": "Basquete", "es": "Baloncesto" } },
    { "emoji": "🎾", "names": { "en": "Tennis", "ar": "تنس", "ja": "テニス", "zh": "网球", "ko": "테니스", "de": "Tennis", "fr": "Tennis", "pt": "Tênis", "es": "Tenis" } },
    { "emoji": "🏊", "names": { "en": "Swimming", "ar": "السباحة", "ja": "水泳", "zh": "游泳", "ko": "수영", "de": "Schwimmen", "fr": "Natation", "pt": "Natação", "es": "Natación" } },
    { "emoji": "🚴", "names": { "en": "Cycling", "ar": "ركوب الدراجات", "ja": "サイクリング", "zh": "骑自行车", "ko": "자전거", "de": "Radfahren", "fr": "Cyclisme", "pt": "Ciclismo", "es": "Ciclismo" } },
    { "emoji": "⛳", "names": { "en": "Golf", "ar": "غولف", "ja": "ゴルフ", "zh": "高尔夫", "ko": "골프", "de": "Golf", "fr": "Golf", "pt": "Golfe", "es": "Golf" } },
    { "emoji": "🥊", "names": { "en": "Boxing", "ar": "الملاكمة", "ja": "ボクシング", "zh": "拳击", "ko": "권투", "de": "Boxen", "fr": "Boxe", "pt": "Boxe", "es": "Boxeo" } },
    { "emoji": "⚾", "names": { "en": "Baseball", "ar": "البيسبول", "ja": "野球", "zh": "棒球", "ko": "야구", "de": "Baseball", "fr": "Baseball", "pt": "Beisebol", "es": "Béisbol" } },
    { "emoji": "⛷️", "names": { "en": "Skiing", "ar": "التزلج", "ja": "スキー", "zh": "滑雪", "ko": "스키", "de": "Skifahren", "fr": "Ski", "pt": "Esqui", "es": "Esquí" } },
    { "emoji": "🏋️", "names": { "en": "Weightlifting", "ar": "رفع الأثقال", "ja": "重量挙げ", "zh": "举重", "ko": "역도", "de": "Gewichtheben", "fr": "Haltérophilie", "pt": "Levantamento de Peso", "es": "Halterofilia" } },
    { "emoji": "🏐", "names": { "en": "Volleyball", "ar": "كرة الطائرة", "ja": "バレーボール", "zh": "排球", "ko": "배구", "de": "Volleyball", "fr": "Volleyball", "pt": "Vôlei", "es": "Voleibol" } },
    { "emoji": "🏉", "names": { "en": "Rugby", "ar": "الرغبي", "ja": "ラグビー", "zh": "橄榄球", "ko": "럭비", "de": "Rugby", "fr": "Rugby", "pt": "Rugby", "es": "Rugby" } },
    { "emoji": "🏏", "names": { "en": "Cricket", "ar": "الكريكيت", "ja": "クリケット", "zh": "板球", "ko": "크리켓", "de": "Cricket", "fr": "Cricket", "pt": "Críquete", "es": "Críquet" } },
    { "emoji": "🏄", "names": { "en": "Surfing", "ar": "ركوب الأمواج", "ja": "サーフィン", "zh": "冲浪", "ko": "서핑", "de": "Surfen", "fr": "Surf", "pt": "Surfe", "es": "Surf" } },
    { "emoji": "🤸", "names": { "en": "Gymnastics", "ar": "الجمباز", "ja": "体操", "zh": "体操", "ko": "체조", "de": "Turnen", "fr": "Gymnastique", "pt": "Ginástica", "es": "Gimnasia" } },
    { "emoji": "🏹", "names": { "en": "Archery", "ar": "الرماية", "ja": "アーチェリー", "zh": "射箭", "ko": "양궁", "de": "Bogenschießen", "fr": "Tir à l'arc", "pt": "Tiro com arco", "es": "Tiro con arco" } },
    { "emoji": "🤺", "names": { "en": "Fencing", "ar": "المبارزة", "ja": "フェンシング", "zh": "击剑", "ko": "펜싱", "de": "Fechten", "fr": "Escrime", "pt": "Esgrima", "es": "Esgrima" } },
    { "emoji": "🏓", "names": { "en": "Table Tennis", "ar": "تنس الطاولة", "ja": "卓球", "zh": "乒乓球", "ko": "탁구", "de": "Tischtennis", "fr": "Tennis de table", "pt": "Tênis de Mesa", "es": "Tenis de mesa" } },
    { "emoji": "🏒", "names": { "en": "Ice Hockey", "ar": "هوكي الجليد", "ja": "アイスホッケー", "zh": "冰球", "ko": "아이스하키", "de": "Eishockey", "fr": "Hockey sur glace", "pt": "Hóquei no gelo", "es": "Hockey sobre hielo" } },
    { "emoji": "🤼", "names": { "en": "Wrestling", "ar": "المصارعة", "ja": "レスリング", "zh": "摔跤", "ko": "레슬링", "de": "Ringen", "fr": "Lutte", "pt": "Luta livre", "es": "Lucha libre" } },
    { "emoji": "🥋", "names": { "en": "Judo", "ar": "الجودو", "ja": "柔道", "zh": "柔道", "ko": "유도", "de": "Judo", "fr": "Judo", "pt": "Judô", "es": "Judo" } },
    { "emoji": "🏸", "names": { "en": "Badminton", "ar": "الريشة الطائرة", "ja": "バドミントン", "zh": "羽毛球", "ko": "배드민턴", "de": "Badminton", "fr": "Badminton", "pt": "Badminton", "es": "Bádminton" } },
    { "emoji": "🧗", "names": { "en": "Rock Climbing", "ar": "تسلق الصخور", "ja": "ロッククライミング", "zh": "攀岩", "ko": "암벽등반", "de": "Klettern", "fr": "Escalade", "pt": "Escalada", "es": "Escalada" } },
    { "emoji": "🛹", "names": { "en": "Skateboarding", "ar": "التزلج على الألواح", "ja": "スケートボード", "zh": "滑板", "ko": "스케이트보드", "de": "Skateboarden", "fr": "Skateboard", "pt": "Skate", "es": "Patineta" } },
    { "emoji": "🏇", "names": { "en": "Horse Riding", "ar": "ركوب الخيل", "ja": "乗马", "zh": "骑马", "ko": "승마", "de": "Reiten", "fr": "Équitation", "pt": "Equitação", "es": "Equitación" } },
    { "emoji": "🤿", "names": { "en": "Diving", "ar": "الغوص", "ja": "ダイビング", "zh": "跳水", "ko": "다이빙", "de": "Tauchen", "fr": "Plongée", "pt": "Mergulho", "es": "Buceo" } },
    { "emoji": "🚣", "names": { "en": "Rowing", "ar": "التجديف", "ja": "ボート漕ぎ", "zh": "划船", "ko": "조정", "de": "Rudern", "fr": "Aviron", "pt": "Remo", "es": "Remo" } },
    { "emoji": "🏂", "names": { "en": "Snowboarding", "ar": "التزلج على الثلج", "ja": "スノーボード", "zh": "单板滑雪", "ko": "스노보드", "de": "Snowboarden", "fr": "Snowboard", "pt": "Snowboard", "es": "Snowboard" } },
    { "emoji": "🤾", "names": { "en": "Handball", "ar": "كرة اليد", "ja": "ハンドボール", "zh": "手球", "ko": "핸드볼", "de": "Handball", "fr": "Handball", "pt": "Handebol", "es": "Balonmano" } }
  ],
  "vehicles": [
    { "emoji": "✈️", "names": { "en": "Airplane", "ar": "طائرة", "ja": "飛行機", "zh": "飞机", "ko": "비행기", "de": "Flugzeug", "fr": "Avion", "pt": "Avião", "es": "Avión" } },
    { "emoji": "🚂", "names": { "en": "Train", "ar": "قطار", "ja": "電車", "zh": "火车", "ko": "기차", "de": "Zug", "fr": "Train", "pt": "Trem", "es": "Tren" } },
    { "emoji": "⛵", "names": { "en": "Sailboat", "ar": "قارب شراعي", "ja": "帆船", "zh": "帆船", "ko": "범선", "de": "Segelboot", "fr": "Voilier", "pt": "Veleiro", "es": "Velero" } },
    { "emoji": "🚁", "names": { "en": "Helicopter", "ar": "مروحية", "ja": "ヘリコプター", "zh": "直升机", "ko": "헬리콥터", "de": "Hubschrauber", "fr": "Hélicoptère", "pt": "Helicóptero", "es": "Helicóptero" } },
    { "emoji": "🏍️", "names": { "en": "Motorcycle", "ar": "دراجة نارية", "ja": "バイク", "zh": "摩托车", "ko": "오토바이", "de": "Motorrad", "fr": "Moto", "pt": "Moto", "es": "Moto" } },
    { "emoji": "🚀", "names": { "en": "Rocket", "ar": "صاروخ", "ja": "ロケット", "zh": "火箭", "ko": "로켓", "de": "Rakete", "fr": "Fusée", "pt": "Foguete", "es": "Cohete" } },
    { "emoji": "🎈", "names": { "en": "Hot Air Balloon", "ar": "منطاد", "ja": "熱気球", "zh": "热气球", "ko": "열기구", "de": "Heißluftballon", "fr": "Montgolfière", "pt": "Balão", "es": "Globo" } },
    { "emoji": "🚢", "names": { "en": "Ship", "ar": "سفينة", "ja": "船", "zh": "轮船", "ko": "선박", "de": "Schiff", "fr": "Navire", "pt": "Navio", "es": "Barco" } },
    { "emoji": "🚲", "names": { "en": "Bicycle", "ar": "دراجة هوائية", "ja": "自転車", "zh": "自行车", "ko": "자전거", "de": "Fahrrad", "fr": "Vélo", "pt": "Bicicleta", "es": "Bicicleta" } },
    { "emoji": "🚗", "names": { "en": "Car", "ar": "سيارة", "ja": "車", "zh": "汽车", "ko": "자동차", "de": "Auto", "fr": "Voiture", "pt": "Carro", "es": "Coche" } },
    { "emoji": "🚢", "names": { "en": "Submarine", "ar": "غواصة", "ja": "潜水艦", "zh": "潜水艇", "ko": "잠수함", "de": "U-Boot", "fr": "Sous-marin", "pt": "Submarino", "es": "Submarino" } },
    { "emoji": "🚡", "names": { "en": "Cable Car", "ar": "تلفريك", "ja": "ケーブルカー", "zh": "缆车", "ko": "케이블카", "de": "Seilbahn", "fr": "Téléphérique", "pt": "Teleférico", "es": "Teleférico" } },
    { "emoji": "🛶", "names": { "en": "Canoe", "ar": "زورق كانو", "ja": "カヌー", "zh": "独木舟", "ko": "카누", "de": "Kanu", "fr": "Canoë", "pt": "Canoa", "es": "Canoa" } },
    { "emoji": "🚕", "names": { "en": "Taxi", "ar": "تاكسي", "ja": "タクシー", "zh": "出租车", "ko": "택시", "de": "Taxi", "fr": "Taxi", "pt": "Táxi", "es": "Taxi" } },
    { "emoji": "🚌", "names": { "en": "Bus", "ar": "حافلة", "ja": "バス", "zh": "公共汽车", "ko": "버스", "de": "Bus", "fr": "Bus", "pt": "Ônibus", "es": "Autobús" } },
    { "emoji": "🚒", "names": { "en": "Fire Truck", "ar": "سيارة الإطفاء", "ja": "消防車", "zh": "消防车", "ko": "소방차", "de": "Feuerwehrauto", "fr": "Camion de pompiers", "pt": "Caminhão de bombeiros", "es": "Camión de bomberos" } },
    { "emoji": "🚑", "names": { "en": "Ambulance", "ar": "سيارة إسعاف", "ja": "救急車", "zh": "救护车", "ko": "구급차", "de": "Krankenwagen", "fr": "Ambulance", "pt": "Ambulância", "es": "Ambulancia" } },
    { "emoji": "🛵", "names": { "en": "Scooter", "ar": "سكوتر", "ja": "スクーター", "zh": "摩托车", "ko": "스쿠터", "de": "Roller", "fr": "Scooter", "pt": "Scooter", "es": "Scooter" } },
    { "emoji": "🚜", "names": { "en": "Tractor", "ar": "جرار زراعي", "ja": "トラクター", "zh": "拖拉机", "ko": "트랙터", "de": "Traktor", "fr": "Tracteur", "pt": "Trator", "es": "Tractor" } },
    { "emoji": "🛸", "names": { "en": "UFO", "ar": "طبق طائر", "ja": "UFO", "zh": "飞碟", "ko": "UFO", "de": "UFO", "fr": "OVNI", "pt": "OVNI", "es": "OVNI" } },
    { "emoji": "🚂", "names": { "en": "Tram", "ar": "ترام", "ja": "路面電車", "zh": "有轨电车", "ko": "트램", "de": "Straßenbahn", "fr": "Tramway", "pt": "Bonde", "es": "Tranvía" } },
    { "emoji": "🛺", "names": { "en": "Tuk-Tuk", "ar": "توك توك", "ja": "トゥクトゥク", "zh": "嘟嘟车", "ko": "툭툭", "de": "Tuk-Tuk", "fr": "Tuk-tuk", "pt": "Tuk-tuk", "es": "Tuk-tuk" } },
    { "emoji": "🚁", "names": { "en": "Space Shuttle", "ar": "مكوك فضائي", "ja": "スペースシャトル", "zh": "航天飞机", "ko": "우주왕복선", "de": "Raumfähre", "fr": "Navette spatiale", "pt": "Ônibus espacial", "es": "Transbordador espacial" } },
    { "emoji": "🛥️", "names": { "en": "Speedboat", "ar": "قارب سريع", "ja": "スピードボート", "zh": "快艇", "ko": "쾌속선", "de": "Schnellboot", "fr": "Hors-bord", "pt": "Lancha", "es": "Lancha" } },
    { "emoji": "🚐", "names": { "en": "Van", "ar": "شاحنة صغيرة", "ja": "バン", "zh": "面包车", "ko": "밴", "de": "Kleinbus", "fr": "Camionnette", "pt": "Van", "es": "Furgoneta" } },
    { "emoji": "🏎️", "names": { "en": "Racing Car", "ar": "سيارة سباق", "ja": "レーシングカー", "zh": "赛车", "ko": "경주차", "de": "Rennwagen", "fr": "Voiture de course", "pt": "Carro de corrida", "es": "Coche de carreras" } },
    { "emoji": "🛩️", "names": { "en": "Private Jet", "ar": "طائرة خاصة", "ja": "プライベートジェット", "zh": "私人飞机", "ko": "전용기", "de": "Privatjet", "fr": "Jet privé", "pt": "Jato particular", "es": "Jet privado" } },
    { "emoji": "🚟", "names": { "en": "Monorail", "ar": "مترو أحادي", "ja": "モノレール", "zh": "单轨列车", "ko": "모노레일", "de": "Monorail", "fr": "Monorail", "pt": "Monotrilho", "es": "Monorraíl" } },
    { "emoji": "🚠", "names": { "en": "Mountain Cablecar", "ar": "تلفريك جبلي", "ja": "山岳ケーブルカー", "zh": "山地缆车", "ko": "산악 케이블카", "de": "Bergbahn", "fr": "Télécabine", "pt": "Bondinho", "es": "Funicular" } }
  ],
  "clothing": [
    { "emoji": "👘", "names": { "en": "Kimono", "ar": "كيمونو", "ja": "着物", "zh": "和服", "ko": "기모노", "de": "Kimono", "fr": "Kimono", "pt": "Quimono", "es": "Kimono" } },
    { "emoji": "👖", "names": { "en": "Jeans", "ar": "جينز", "ja": "ジーンズ", "zh": "牛仔裤", "ko": "청바지", "de": "Jeans", "fr": "Jean", "pt": "Jeans", "es": "Jeans" } },
    { "emoji": "🕶️", "names": { "en": "Sunglasses", "ar": "نظارات شمسية", "ja": "サングラス", "zh": "太阳镜", "ko": "선글라스", "de": "Sonnenbrille", "fr": "Lunettes de soleil", "pt": "Óculos de sol", "es": "Gafas de sol" } },
    { "emoji": "👑", "names": { "en": "Crown", "ar": "تاج", "ja": "王冠", "zh": "皇冠", "ko": "왕관", "de": "Krone", "fr": "Couronne", "pt": "Coroa", "es": "Corona" } },
    { "emoji": "👢", "names": { "en": "Boots", "ar": "حذاء بوت", "ja": "ブーツ", "zh": "靴子", "ko": "부츠", "de": "Stiefel", "fr": "Bottes", "pt": "Botas", "es": "Botas" } },
    { "emoji": "🧣", "names": { "en": "Scarf", "ar": "وشاح", "ja": "スカーフ", "zh": "围巾", "ko": "스카프", "de": "Schal", "fr": "Écharpe", "pt": "Cachecol", "es": "Bufanda" } },
    { "emoji": "🎩", "names": { "en": "Top Hat", "ar": "قبعة سيلندر", "ja": "シルクハット", "zh": "礼帽", "ko": "실크 모자", "de": "Zylinder", "fr": "Haut-de-forme", "pt": "Cartola", "es": "Chistera" } },
    { "emoji": "👙", "names": { "en": "Bikini", "ar": "بيكيني", "ja": "ビキニ", "zh": "比基尼", "ko": "비키니", "de": "Bikini", "fr": "Bikini", "pt": "Biquíni", "es": "Bikini" } },
    { "emoji": "👕", "names": { "en": "T-Shirt", "ar": "تيشيرت", "ja": "Tシャツ", "zh": "T恤", "ko": "티셔츠", "de": "T-Shirt", "fr": "T-shirt", "pt": "Camiseta", "es": "Camiseta" } },
    { "emoji": "👗", "names": { "en": "Dress", "ar": "فستان", "ja": "ドレス", "zh": "连衣裙", "ko": "드레스", "de": "Kleid", "fr": "Robe", "pt": "Vestido", "es": "Vestido" } },
    { "emoji": "🤵", "names": { "en": "Suit", "ar": "بدلة", "ja": "スーツ", "zh": "西装", "ko": "정장", "de": "Anzug", "fr": "Costume", "pt": "Terno", "es": "Traje" } },
    { "emoji": "🥿", "names": { "en": "Sandals", "ar": "صندل", "ja": "サンダル", "zh": "凉鞋", "ko": "샌들", "de": "Sandalen", "fr": "Sandales", "pt": "Sandálias", "es": "Sandalias" } },
    { "emoji": "🧤", "names": { "en": "Gloves", "ar": "قفازات", "ja": "手袋", "zh": "手套", "ko": "장갑", "de": "Handschuhe", "fr": "Gants", "pt": "Luvas", "es": "Guantes" } },
    { "emoji": "🥻", "names": { "en": "Sari", "ar": "ساري", "ja": "サリー", "zh": "纱丽", "ko": "사리", "de": "Sari", "fr": "Sari", "pt": "Sari", "es": "Sari" } },
    { "emoji": "🎓", "names": { "en": "Graduation Cap", "ar": "قبعة التخرج", "ja": "卒業帽", "zh": "学士帽", "ko": "졸업모자", "de": "Doktorhut", "fr": "Toque de diplôme", "pt": "Capelo", "es": "Birrete" } },
    { "emoji": "🧢", "names": { "en": "Cap", "ar": "قبعة كاب", "ja": "キャップ", "zh": "棒球帽", "ko": "모자", "de": "Kappe", "fr": "Casquette", "pt": "Boné", "es": "Gorra" } },
    { "emoji": "🥾", "names": { "en": "Hiking Boots", "ar": "حذاء التنزه", "ja": "ハイキングブーツ", "zh": "登山靴", "ko": "등산화", "de": "Wanderstiefel", "fr": "Chaussures de randonnée", "pt": "Bota de trilha", "es": "Bota de senderismo" } },
    { "emoji": "🩲", "names": { "en": "Shorts", "ar": "شورت", "ja": "ショーツ", "zh": "短裤", "ko": "반바지", "de": "Shorts", "fr": "Short", "pt": "Shorts", "es": "Pantalón corto" } },
    { "emoji": "🧥", "names": { "en": "Raincoat", "ar": "معطف المطر", "ja": "レインコート", "zh": "雨衣", "ko": "우비", "de": "Regenmantel", "fr": "Imperméable", "pt": "Capa de chuva", "es": "Impermeable" } },
    { "emoji": "👔", "names": { "en": "Tie", "ar": "ربطة عنق", "ja": "ネクタイ", "zh": "领带", "ko": "넥타이", "de": "Krawatte", "fr": "Cravate", "pt": "Gravata", "es": "Corbata" } },
    { "emoji": "👚", "names": { "en": "Hoodie", "ar": "هودي", "ja": "パーカー", "zh": "连帽衫", "ko": "후디", "de": "Hoodie", "fr": "Sweat à capuche", "pt": "Moletom", "es": "Sudadera" } },
    { "emoji": "👞", "names": { "en": "Sneakers", "ar": "حذاء رياضي", "ja": "スニーカー", "zh": "运动鞋", "ko": "운동화", "de": "Turnschuhe", "fr": "Baskets", "pt": "Tênis", "es": "Zapatillas" } },
    { "emoji": "🩱", "names": { "en": "Swimsuit", "ar": "بدلة السباحة", "ja": "水着", "zh": "泳衣", "ko": "수영복", "de": "Badeanzug", "fr": "Maillot de bain", "pt": "Maiô", "es": "Traje de baño" } },
    { "emoji": "🎭", "names": { "en": "Cape", "ar": "رداء", "ja": "マント", "zh": "斗篷", "ko": "망토", "de": "Umhang", "fr": "Cape", "pt": "Capa", "es": "Capa" } },
    { "emoji": "🧦", "names": { "en": "Socks", "ar": "جوارب", "ja": "靴下", "zh": "袜子", "ko": "양말", "de": "Socken", "fr": "Chaussettes", "pt": "Meias", "es": "Calcetines" } },
    { "emoji": "🥼", "names": { "en": "Lab Coat", "ar": "معطف طبي", "ja": "白衣", "zh": "白大褂", "ko": "실험복", "de": "Laborkittel", "fr": "Blouse de labo", "pt": "Jaleco", "es": "Bata de laboratorio" } },
    { "emoji": "🎪", "names": { "en": "Sombrero", "ar": "سومبريرو", "ja": "ソンブレロ", "zh": "宽边帽", "ko": "솜브레로", "de": "Sombrero", "fr": "Sombrero", "pt": "Sombreiro", "es": "Sombrero" } },
    { "emoji": "🧣", "names": { "en": "Turban", "ar": "عمامة", "ja": "ターバン", "zh": "头巾", "ko": "터번", "de": "Turban", "fr": "Turban", "pt": "Turbante", "es": "Turbante" } },
    { "emoji": "🧤", "names": { "en": "Mittens", "ar": "قفاز كامل", "ja": "ミトン", "zh": "连指手套", "ko": "벙어리장갑", "de": "Fäustlinge", "fr": "Moufles", "pt": "Luvas de dedo", "es": "Manoplas" } }
  ],
  "nature": [
    { "emoji": "🌈", "names": { "en": "Rainbow", "ar": "قوس قزح", "ja": "虹", "zh": "彩虹", "ko": "무지개", "de": "Regenbogen", "fr": "Arc-en-ciel", "pt": "Arco-íris", "es": "Arcoíris" } },
    { "emoji": "🌋", "names": { "en": "Volcano", "ar": "بركان", "ja": "火山", "zh": "火山", "ko": "화산", "de": "Vulkan", "fr": "Volcan", "pt": "Vulcão", "es": "Volcán" } },
    { "emoji": "🌌", "names": { "en": "Aurora", "ar": "الشفق القطبي", "ja": "オーロラ", "zh": "极光", "ko": "오로라", "de": "Aurora", "fr": "Aurore", "pt": "Aurora", "es": "Aurora" } },
    { "emoji": "🏜️", "names": { "en": "Desert", "ar": "صحراء", "ja": "砂漠", "zh": "沙漠", "ko": "사막", "de": "Wüste", "fr": "Désert", "pt": "Deserto", "es": "Desierto" } },
    { "emoji": "🏔️", "names": { "en": "Glacier", "ar": "نهر جليدي", "ja": "氷河", "zh": "冰川", "ko": "빙하", "de": "Gletscher", "fr": "Glacier", "pt": "Geleira", "es": "Glaciar" } },
    { "emoji": "🌊", "names": { "en": "Ocean Wave", "ar": "موجة المحيط", "ja": "波", "zh": "海浪", "ko": "파도", "de": "Meereswelle", "fr": "Vague", "pt": "Onda", "es": "Ola" } },
    { "emoji": "🍄", "names": { "en": "Mushroom", "ar": "فطر", "ja": "キノコ", "zh": "蘑菇", "ko": "버섯", "de": "Pilz", "fr": "Champignon", "pt": "Cogumelo", "es": "Hongo" } },
    { "emoji": "🌵", "names": { "en": "Cactus", "ar": "صبار", "ja": "サボテン", "zh": "仙人掌", "ko": "선인장", "de": "Kaktus", "fr": "Cactus", "pt": "Cacto", "es": "Cactus" } },
    { "emoji": "🌊", "names": { "en": "Waterfall", "ar": "شلال", "ja": "滝", "zh": "瀑布", "ko": "폭포", "de": "Wasserfall", "fr": "Cascade", "pt": "Cachoeira", "es": "Cascada" } },
    { "emoji": "🌲", "names": { "en": "Forest", "ar": "غابة", "ja": "森", "zh": "森林", "ko": "숲", "de": "Wald", "fr": "Forêt", "pt": "Floresta", "es": "Bosque" } },
    { "emoji": "🪸", "names": { "en": "Coral Reef", "ar": "شعاب مرجانية", "ja": "サンゴ礁", "zh": "珊瑚礁", "ko": "산호초", "de": "Korallenriff", "fr": "Récif corallien", "pt": "Recife de coral", "es": "Arrecife de coral" } },
    { "emoji": "🌪️", "names": { "en": "Tornado", "ar": "إعصار", "ja": "竜巻", "zh": "龙卷风", "ko": "토네이도", "de": "Tornado", "fr": "Tornade", "pt": "Tornado", "es": "Tornado" } },
    { "emoji": "❄️", "names": { "en": "Snowflake", "ar": "ندفة ثلج", "ja": "雪の結晶", "zh": "雪花", "ko": "눈송이", "de": "Schneeflocke", "fr": "Flocon de neige", "pt": "Floco de neve", "es": "Copo de nieve" } },
    { "emoji": "🕳️", "names": { "en": "Cave", "ar": "كهف", "ja": "洞窟", "zh": "山洞", "ko": "동굴", "de": "Höhle", "fr": "Grotte", "pt": "Caverna", "es": "Cueva" } },
    { "emoji": "🌠", "names": { "en": "Meteor Shower", "ar": "شهب متساقطة", "ja": "流星群", "zh": "流星雨", "ko": "유성우", "de": "Meteoritenschauer", "fr": "Pluie de météores", "pt": "Chuva de meteoros", "es": "Lluvia de meteoros" } },
    { "emoji": "💧", "names": { "en": "Geyser", "ar": "نافورة حرارية", "ja": "間欠泉", "zh": "间歇泉", "ko": "간헐천", "de": "Geysir", "fr": "Geyser", "pt": "Géiser", "es": "Géiser" } },
    { "emoji": "🏖️", "names": { "en": "Sand Dune", "ar": "كثيب رملي", "ja": "砂丘", "zh": "沙丘", "ko": "모래 언덕", "de": "Sanddüne", "fr": "Dune de sable", "pt": "Duna de areia", "es": "Duna de arena" } },
    { "emoji": "⛈️", "names": { "en": "Thunderstorm", "ar": "عاصفة رعدية", "ja": "雷雨", "zh": "雷暴", "ko": "뇌우", "de": "Gewitter", "fr": "Orage", "pt": "Tempestade", "es": "Tormenta eléctrica" } },
    { "emoji": "♨️", "names": { "en": "Hot Spring", "ar": "ينبوع حار", "ja": "温泉", "zh": "温泉", "ko": "온천", "de": "Thermalquelle", "fr": "Source chaude", "pt": "Fonte termal", "es": "Aguas termales" } },
    { "emoji": "🏔️", "names": { "en": "Canyon", "ar": "وادي سحيق", "ja": "峡谷", "zh": "峡谷", "ko": "협곡", "de": "Canyon", "fr": "Canyon", "pt": "Cânion", "es": "Cañón" } },
    { "emoji": "🌿", "names": { "en": "Swamp", "ar": "مستنقع", "ja": "沼地", "zh": "沼泽", "ko": "늪", "de": "Sumpf", "fr": "Marais", "pt": "Pântano", "es": "Pantano" } },
    { "emoji": "🧊", "names": { "en": "Iceberg", "ar": "جبل جليدي", "ja": "氷山", "zh": "冰山", "ko": "빙산", "de": "Eisberg", "fr": "Iceberg", "pt": "Iceberg", "es": "Iceberg" } },
    { "emoji": "🌴", "names": { "en": "Oasis", "ar": "واحة", "ja": "オアシス", "zh": "绿洲", "ko": "오아시스", "de": "Oase", "fr": "Oasis", "pt": "Oásis", "es": "Oasis" } },
    { "emoji": "🌳", "names": { "en": "Jungle", "ar": "غابة استوائية", "ja": "ジャングル", "zh": "丛林", "ko": "정글", "de": "Dschungel", "fr": "Jungle", "pt": "Selva", "es": "Jungla" } },
    { "emoji": "🌸", "names": { "en": "Cherry Blossom", "ar": "أزهار الكرز", "ja": "桜", "zh": "樱花", "ko": "벚꽃", "de": "Kirschblüte", "fr": "Fleur de cerisier", "pt": "Flor de cerejeira", "es": "Flor de cerezo" } },
    { "emoji": "⚡", "names": { "en": "Lightning", "ar": "صاعقة", "ja": "稲妻", "zh": "闪电", "ko": "번개", "de": "Blitz", "fr": "Éclair", "pt": "Relâmpago", "es": "Rayo" } },
    { "emoji": "🌾", "names": { "en": "Prairie", "ar": "سهل عشبي", "ja": "草原", "zh": "草原", "ko": "초원", "de": "Prärie", "fr": "Prairie", "pt": "Pradaria", "es": "Pradera" } },
    { "emoji": "🎋", "names": { "en": "Bamboo Forest", "ar": "غابة الخيزران", "ja": "竹林", "zh": "竹林", "ko": "대나무 숲", "de": "Bambuswald", "fr": "Forêt de bambous", "pt": "Floresta de bambu", "es": "Bosque de bambú" } },
    { "emoji": "🪨", "names": { "en": "Cliff", "ar": "جرف صخري", "ja": "崖", "zh": "悬崖", "ko": "절벽", "de": "Klippe", "fr": "Falaise", "pt": "Penhasco", "es": "Acantilado" } }
  ],
  "movies": [
    { "emoji": "🦁", "names": { "en": "The Lion King", "ar": "الأسد الملك", "ja": "ライオン・キング", "zh": "狮子王", "ko": "라이온 킹", "de": "König der Löwen", "fr": "Roi Lion", "pt": "Rei Leão", "es": "Rey León" } },
    { "emoji": "🚢", "names": { "en": "Titanic", "ar": "تايتانيك", "ja": "タイタニック", "zh": "泰坦尼克号", "ko": "타이타닉", "de": "Titanic", "fr": "Titanic", "pt": "Titanic", "es": "Titanic" } },
    { "emoji": "⚔️", "names": { "en": "Star Wars", "ar": "حرب النجوم", "ja": "スター・ウォーズ", "zh": "星球大战", "ko": "스타워즈", "de": "Star Wars", "fr": "Star Wars", "pt": "Guerra nas Estrelas", "es": "Star Wars" } },
    { "emoji": "🌿", "names": { "en": "Avatar", "ar": "أفاتار", "ja": "アバター", "zh": "阿凡达", "ko": "아바타", "de": "Avatar", "fr": "Avatar", "pt": "Avatar", "es": "Avatar" } },
    { "emoji": "🦕", "names": { "en": "Jurassic Park", "ar": "حديقة الديناصورات", "ja": "ジュラシック・パーク", "zh": "侏罗纪公园", "ko": "쥬라기 공원", "de": "Jurassic Park", "fr": "Jurassic Park", "pt": "Parque dos Dinossauros", "es": "Parque Jurásico" } },
    { "emoji": "⚡", "names": { "en": "Harry Potter", "ar": "هاري بوتر", "ja": "ハリー・ポッター", "zh": "哈利波特", "ko": "해리 포터", "de": "Harry Potter", "fr": "Harry Potter", "pt": "Harry Potter", "es": "Harry Potter" } },
    { "emoji": "❄️", "names": { "en": "Frozen", "ar": "ملكة الثلج", "ja": "アナと雪の女王", "zh": "冰雪奇缘", "ko": "겨울왕국", "de": "Die Eiskönigin", "fr": "Reine des Neiges", "pt": "Frozen", "es": "Frozen" } },
    { "emoji": "🕷️", "names": { "en": "Spider-Man", "ar": "سبايدر مان", "ja": "スパイダーマン", "zh": "蜘蛛侠", "ko": "스파이더맨", "de": "Spider-Man", "fr": "Spider-Man", "pt": "Homem-Aranha", "es": "Spider-Man" } },
    { "emoji": "🦸", "names": { "en": "The Avengers", "ar": "المنتقمون", "ja": "アベンジャーズ", "zh": "复仇者联盟", "ko": "어벤져스", "de": "Die Avengers", "fr": "Les Avengers", "pt": "Os Vingadores", "es": "Los Vengadores" } },
    { "emoji": "🧸", "names": { "en": "Toy Story", "ar": "قصة لعبة", "ja": "トイ・ストーリー", "zh": "玩具总动员", "ko": "토이 스토리", "de": "Toy Story", "fr": "Toy Story", "pt": "Toy Story", "es": "Toy Story" } },
    { "emoji": "🦇", "names": { "en": "The Dark Knight", "ar": "فارس الظلام", "ja": "ダークナイト", "zh": "蝙蝠侠", "ko": "다크 나이트", "de": "The Dark Knight", "fr": "The Dark Knight", "pt": "O Cavaleiro das Trevas", "es": "El Caballero Oscuro" } },
    { "emoji": "🌌", "names": { "en": "Interstellar", "ar": "بين النجوم", "ja": "インターステラー", "zh": "星际穿越", "ko": "인터스텔라", "de": "Interstellar", "fr": "Interstellar", "pt": "Interestelar", "es": "Interestelar" } },
    { "emoji": "💊", "names": { "en": "The Matrix", "ar": "ماتريكس", "ja": "マトリックス", "zh": "黑客帝国", "ko": "매트릭스", "de": "Matrix", "fr": "Matrix", "pt": "Matrix", "es": "Matrix" } },
    { "emoji": "🐟", "names": { "en": "Finding Nemo", "ar": "البحث عن نيمو", "ja": "ファインディング・ニモ", "zh": "海底总动员", "ko": "니모를 찾아서", "de": "Findet Nemo", "fr": "Le Monde de Nemo", "pt": "Procurando Nemo", "es": "Buscando a Nemo" } },
    { "emoji": "🧅", "names": { "en": "Shrek", "ar": "شريك", "ja": "シュレック", "zh": "怪物史莱克", "ko": "슈렉", "de": "Shrek", "fr": "Shrek", "pt": "Shrek", "es": "Shrek" } },
    { "emoji": "🐼", "names": { "en": "Kung Fu Panda", "ar": "الباندا الكونفو", "ja": "カンフー・パンダ", "zh": "功夫熊猫", "ko": "쿵푸팬더", "de": "Kung Fu Panda", "fr": "Kung Fu Panda", "pt": "Kung Fu Panda", "es": "Kung Fu Panda" } },
    { "emoji": "🌊", "names": { "en": "Moana", "ar": "موانا", "ja": "モアナと伝説の海", "zh": "海洋奇缘", "ko": "모아나", "de": "Moana", "fr": "Vaiana", "pt": "Moana", "es": "Moana" } },
    { "emoji": "🐆", "names": { "en": "Black Panther", "ar": "الفهد الأسود", "ja": "ブラックパンサー", "zh": "黑豹", "ko": "블랙 팬서", "de": "Black Panther", "fr": "Black Panther", "pt": "Pantera Negra", "es": "Pantera Negra" } },
    { "emoji": "💤", "names": { "en": "Inception", "ar": "أصل الخيال", "ja": "インセプション", "zh": "盗梦空间", "ko": "인셉션", "de": "Inception", "fr": "Inception", "pt": "A Origem", "es": "El Origen" } },
    { "emoji": "💀", "names": { "en": "Coco", "ar": "كوكو", "ja": "リメンバー・ミー", "zh": "寻梦环游记", "ko": "코코", "de": "Coco", "fr": "Coco", "pt": "Viva", "es": "Coco" } },
    { "emoji": "🎈", "names": { "en": "Up", "ar": "فوق السحاب", "ja": "カールじいさんの空飛ぶ家", "zh": "飞屋环游记", "ko": "업", "de": "Oben", "fr": "Là-haut", "pt": "Up", "es": "Up" } },
    { "emoji": "🤖", "names": { "en": "Wall-E", "ar": "وولي", "ja": "ウォーリー", "zh": "机器人总动员", "ko": "월-E", "de": "Wall·E", "fr": "WALL-E", "pt": "WALL-E", "es": "WALL-E" } },
    { "emoji": "💍", "names": { "en": "Lord of the Rings", "ar": "سيد الخواتم", "ja": "指輪物語", "zh": "指环王", "ko": "반지의 제왕", "de": "Der Herr der Ringe", "fr": "Le Seigneur des Anneaux", "pt": "O Senhor dos Anéis", "es": "El Señor de los Anillos" } },
    { "emoji": "🏎️", "names": { "en": "Fast & Furious", "ar": "السرعة والغضب", "ja": "ワイルド・スピード", "zh": "速度与激情", "ko": "분노의 질주", "de": "Fast & Furious", "fr": "Fast & Furious", "pt": "Velocidade Furiosa", "es": "Rápidos y Furiosos" } },
    { "emoji": "😈", "names": { "en": "Despicable Me", "ar": "أنا الشرير", "ja": "怪盗グルーの月泥棒", "zh": "神偷奶爸", "ko": "슈퍼배드", "de": "Ich — Einfach unverbesserlich", "fr": "Moi, moche et méchant", "pt": "Meu Malvado Favorito", "es": "Mi Villano Favorito" } },
    { "emoji": "🏠", "names": { "en": "Home Alone", "ar": "وحيد في المنزل", "ja": "ホーム・アローン", "zh": "小鬼当家", "ko": "나 홀로 집에", "de": "Kevin — Allein zu Haus", "fr": "Maman, j'ai raté l'avion", "pt": "Esqueceram de Mim", "es": "Solo en Casa" } },
    { "emoji": "🤺", "names": { "en": "Gladiator", "ar": "المصارع", "ja": "グラディエーター", "zh": "角斗士", "ko": "글래디에이터", "de": "Gladiator", "fr": "Gladiateur", "pt": "Gladiador", "es": "Gladiador" } },
    { "emoji": "🌹", "names": { "en": "Beauty and the Beast", "ar": "الجميلة والوحش", "ja": "美女と野獣", "zh": "美女与野兽", "ko": "미녀와 야수", "de": "Die Schöne und das Biest", "fr": "La Belle et la Bête", "pt": "A Bela e a Fera", "es": "La Bella y la Bestia" } },
    { "emoji": "❤️", "names": { "en": "Grease", "ar": "جريس", "ja": "グリース", "zh": "油脂", "ko": "그리스", "de": "Grease", "fr": "Grease", "pt": "Grease", "es": "Grease" } }
  ],
  "music": [
    { "emoji": "🎸", "names": { "en": "Guitar", "ar": "غيتار", "ja": "ギター", "zh": "吉他", "ko": "기타", "de": "Gitarre", "fr": "Guitare", "pt": "Violão", "es": "Guitarra" } },
    { "emoji": "🎹", "names": { "en": "Piano", "ar": "بيانو", "ja": "ピアノ", "zh": "钢琴", "ko": "피아노", "de": "Klavier", "fr": "Piano", "pt": "Piano", "es": "Piano" } },
    { "emoji": "🥁", "names": { "en": "Drums", "ar": "طبول", "ja": "ドラム", "zh": "鼓", "ko": "드럼", "de": "Schlagzeug", "fr": "Batterie", "pt": "Bateria", "es": "Batería" } },
    { "emoji": "🎻", "names": { "en": "Violin", "ar": "كمان", "ja": "バイオリン", "zh": "小提琴", "ko": "바이올린", "de": "Geige", "fr": "Violon", "pt": "Violino", "es": "Violín" } },
    { "emoji": "🎺", "names": { "en": "Trumpet", "ar": "بوق", "ja": "トランペット", "zh": "小号", "ko": "트럼펫", "de": "Trompete", "fr": "Trompette", "pt": "Trompete", "es": "Trompeta" } },
    { "emoji": "🎤", "names": { "en": "Microphone", "ar": "ميكروفون", "ja": "マイク", "zh": "麦克风", "ko": "마이크", "de": "Mikrofon", "fr": "Microphone", "pt": "Microfone", "es": "Micrófono" } },
    { "emoji": "🎧", "names": { "en": "Headphones", "ar": "سماعات", "ja": "ヘッドフォン", "zh": "耳机", "ko": "헤드폰", "de": "Kopfhörer", "fr": "Casque", "pt": "Fone de Ouvido", "es": "Auriculares" } },
    { "emoji": "🪗", "names": { "en": "Accordion", "ar": "أكورديون", "ja": "アコーディオン", "zh": "手风琴", "ko": "아코디언", "de": "Akkordeon", "fr": "Accordéon", "pt": "Acordeão", "es": "Acordeón" } },
    { "emoji": "🎸", "names": { "en": "Bass Guitar", "ar": "جيتار باس", "ja": "ベースギター", "zh": "贝斯吉他", "ko": "베이스 기타", "de": "Bassgitarre", "fr": "Guitare basse", "pt": "Guitarra baixo", "es": "Bajo" } },
    { "emoji": "🎶", "names": { "en": "Flute", "ar": "ناي", "ja": "フルート", "zh": "长笛", "ko": "플루트", "de": "Flöte", "fr": "Flûte", "pt": "Flauta", "es": "Flauta" } },
    { "emoji": "🎷", "names": { "en": "Saxophone", "ar": "ساكسوفون", "ja": "サックス", "zh": "萨克斯", "ko": "색소폰", "de": "Saxophon", "fr": "Saxophone", "pt": "Saxofone", "es": "Saxofón" } },
    { "emoji": "🎻", "names": { "en": "Cello", "ar": "تشيلو", "ja": "チェロ", "zh": "大提琴", "ko": "첼로", "de": "Cello", "fr": "Violoncelle", "pt": "Violoncelo", "es": "Violonchelo" } },
    { "emoji": "🪘", "names": { "en": "Bongo Drums", "ar": "طبول بونغو", "ja": "ボンゴ", "zh": "邦戈鼓", "ko": "봉고", "de": "Bongos", "fr": "Bongos", "pt": "Bongô", "es": "Bongó" } },
    { "emoji": "🎵", "names": { "en": "Harp", "ar": "قيثارة", "ja": "ハープ", "zh": "竖琴", "ko": "하프", "de": "Harfe", "fr": "Harpe", "pt": "Harpa", "es": "Arpa" } },
    { "emoji": "🪕", "names": { "en": "Ukulele", "ar": "يوكيليلي", "ja": "ウクレレ", "zh": "尤克里里", "ko": "우쿨렐레", "de": "Ukulele", "fr": "Ukulélé", "pt": "Ukulelê", "es": "Ukelele" } },
    { "emoji": "🎙️", "names": { "en": "Turntable", "ar": "طاولة الخلط", "ja": "ターンテーブル", "zh": "转盘", "ko": "턴테이블", "de": "Plattenspieler", "fr": "Platine vinyle", "pt": "Toca-discos", "es": "Giradiscos" } },
    { "emoji": "🎹", "names": { "en": "Synthesizer", "ar": "سينثيسايزر", "ja": "シンセサイザー", "zh": "合成器", "ko": "신시사이저", "de": "Synthesizer", "fr": "Synthétiseur", "pt": "Sintetizador", "es": "Sintetizador" } },
    { "emoji": "🎼", "names": { "en": "Harmonica", "ar": "هارمونيكا", "ja": "ハーモニカ", "zh": "口琴", "ko": "하모니카", "de": "Mundharmonika", "fr": "Harmonica", "pt": "Gaita", "es": "Armónica" } },
    { "emoji": "🎺", "names": { "en": "Bagpipes", "ar": "مزمار القربة", "ja": "バグパイプ", "zh": "风笛", "ko": "백파이프", "de": "Dudelsack", "fr": "Cornemuse", "pt": "Gaita de foles", "es": "Gaita" } },
    { "emoji": "🎵", "names": { "en": "Xylophone", "ar": "زيلوفون", "ja": "木琴", "zh": "木琴", "ko": "실로폰", "de": "Xylophon", "fr": "Xylophone", "pt": "Xilofone", "es": "Xilófono" } },
    { "emoji": "🪗", "names": { "en": "Sitar", "ar": "سيتار", "ja": "シタール", "zh": "西塔琴", "ko": "시타르", "de": "Sitar", "fr": "Sitar", "pt": "Sitar", "es": "Sitar" } },
    { "emoji": "🥁", "names": { "en": "Tambourine", "ar": "دف", "ja": "タンバリン", "zh": "铃鼓", "ko": "탬버린", "de": "Tamburin", "fr": "Tambourin", "pt": "Pandeiro", "es": "Pandereta" } },
    { "emoji": "🎸", "names": { "en": "Concert", "ar": "حفل موسيقي", "ja": "コンサート", "zh": "音乐会", "ko": "콘서트", "de": "Konzert", "fr": "Concert", "pt": "Show", "es": "Concierto" } },
    { "emoji": "🎉", "names": { "en": "Music Festival", "ar": "مهرجان موسيقي", "ja": "音楽フェス", "zh": "音乐节", "ko": "음악 페스티벌", "de": "Musikfestival", "fr": "Festival de musique", "pt": "Festival de música", "es": "Festival de música" } },
    { "emoji": "🎭", "names": { "en": "Opera", "ar": "أوبرا", "ja": "オペラ", "zh": "歌剧", "ko": "오페라", "de": "Oper", "fr": "Opéra", "pt": "Ópera", "es": "Ópera" } },
    { "emoji": "🎤", "names": { "en": "Karaoke", "ar": "كاريوكي", "ja": "カラオケ", "zh": "卡拉OK", "ko": "노래방", "de": "Karaoke", "fr": "Karaoké", "pt": "Karaokê", "es": "Karaoke" } },
    { "emoji": "📻", "names": { "en": "Record Player", "ar": "مشغل الأسطوانات", "ja": "レコードプレーヤー", "zh": "唱片机", "ko": "레코드 플레이어", "de": "Plattenspieler", "fr": "Tourne-disque", "pt": "Vitrola", "es": "Tocadiscos" } },
    { "emoji": "🎵", "names": { "en": "Music Box", "ar": "صندوق موسيقي", "ja": "オルゴール", "zh": "音乐盒", "ko": "오르골", "de": "Spieluhr", "fr": "Boîte à musique", "pt": "Caixinha de música", "es": "Caja de música" } },
    { "emoji": "📺", "names": { "en": "Music Video", "ar": "فيديو كليب", "ja": "ミュージックビデオ", "zh": "音乐视频", "ko": "뮤직비디오", "de": "Musikvideo", "fr": "Clip vidéo", "pt": "Videoclipe", "es": "Videoclip" } }
  ]
};

export const CATEGORY_NAMES = {
  "food":      { "en": "Food", "ar": "طعام", "ja": "食べ物", "zh": "食物", "ko": "음식", "de": "Essen", "fr": "Nourriture", "pt": "Comida", "es": "Comida" },
  "animals":   { "en": "Animals", "ar": "حيوانات", "ja": "動物", "zh": "动物", "ko": "동물", "de": "Tiere", "fr": "Animaux", "pt": "Animais", "es": "Animales" },
  "countries": { "en": "Countries", "ar": "دول", "ja": "国", "zh": "国家", "ko": "국가", "de": "Länder", "fr": "Pays", "pt": "Países", "es": "Países" },
  "sports":    { "en": "Sports", "ar": "رياضة", "ja": "スポーツ", "zh": "体育", "ko": "스포츠", "de": "Sport", "fr": "Sports", "pt": "Esportes", "es": "Deportes" },
  "vehicles":  { "en": "Vehicles", "ar": "مركبات", "ja": "乗り物", "zh": "交通工具", "ko": "탈것", "de": "Fahrzeuge", "fr": "Véhicules", "pt": "Veículos", "es": "Vehículos" },
  "clothing":  { "en": "Clothing", "ar": "ملابس", "ja": "服", "zh": "服装", "ko": "옷", "de": "Kleidung", "fr": "Vêtements", "pt": "Roupas", "es": "Ropa" },
  "nature":    { "en": "Nature", "ar": "طبيعة", "ja": "自然", "zh": "自然", "ko": "자연", "de": "Natur", "fr": "Nature", "pt": "Natureza", "es": "Naturaleza" },
  "movies":    { "en": "Movies", "ar": "أفلام", "ja": "映画", "zh": "电影", "ko": "영화", "de": "Filme", "fr": "Films", "pt": "Filmes", "es": "Películas" },
  "music":     { "en": "Music", "ar": "موسيقى", "ja": "音楽", "zh": "音乐", "ko": "음악", "de": "Musik", "fr": "Musique", "pt": "Música", "es": "Música" },
  "custom":    { "en": "Custom", "ar": "مخصص", "ja": "カスタム", "zh": "自定义", "ko": "사용자 지정", "de": "Benutzerdefiniert", "fr": "Personnalisé", "pt": "Personalizado", "es": "Personalizado" }
};
